### ISSUE TITLE
Cannot Send Session Cookie

### ISSUE THREAD

**Issue by mattharwood** [datenbrei/blogless#1]
Hi there,

Having trouble on PHP 5.6, passing all the /admin tests on first load, but the following error is presented. When clicking on the continue button, I only get a white page with the same error, no other content.

 Warning: session_start(): Cannot send session cookie - headers already sent by (output started at /var/sites/m/EXAMPLE.com/public_html/admin/index.php:1) in /var/sites/m/EXAMPLE.com/public_html/admin/auth.php on line 10

Warning: session_start(): Cannot send session cache limiter - headers already sent (output started at /var/sites/m/EXAMPLE.com/public_html/admin/index.php:1) in /var/sites/m/EXAMPLE.com/public_html/admin/auth.php on line 10

Warning: Cannot modify header information - headers already sent by (output started at /var/sites/m/EXAMPLE.com/public_html/admin/index.php:1) in /var/sites/m/EXAMPLE.com/public_html/admin/auth.php on line 17
Access denied

Any help much appreciated!

**Comment by datenbrei** [comment]
Hi 

i will have a look at it. You are using the original files? Never loaded in an editor?

## Ciao, Martin

Martin Döring - http://martin.datenbrei.de

Am 11. April 2016 22:20:07 MESZ, schrieb mattharwood notifications@github.com:

**Comment by meichuan** [comment]
Comment out the die statement in auth.php file. Works for me.

**Comment by Zegnat** [comment]
Haven’t had time to test it yet, but here is my hypothesis:

`config.php` ends with an extra linebreak and is included (through `include.php`) before `auth.php` runs. This means that, unless your server is configured to always use PHP `output_buffering` there is already a linebreak sent to the browser before you are trying to send another HTTP header.

To get around these sort of problems it is recommended to just omit `?>` tags on 100% PHP files like those here. This has also been [adopted by the PSR-2 coding standard](http://www.php-fig.org/psr/psr-2/#2-2-files) and with that by many other mayor PHP projects. That might be something to consider for blogless as well.

**Comment by Zegnat** [comment]
I was wrong, it had nothing to do with spaces (this time) but with the inclusion of UTF-8 BOM in `index.php`. Pull request sent.

Note to @datenbrei, if you want to reproduce this error you can easily do so using PHP’s built-in server as long as you turn off output buffering:

```
php -S localhost:1234 -d output_buffering=0
```
