### ISSUE TITLE
How to run from sub-directory

### ISSUE THREAD

**Issue by tyeeman** [datenbrei/blogless#3]
I need to run this from a sub-directory. Can htaccess be modified to enable this? Nice work, looks great!

It's strange because in the admin, the urls for editing do show the sub-directory and editing works fine. It's just on the main page, the links to view do not show the sub-directory.

**Comment by datenbrei** [comment]
I fixed this. Just made the pathes on the index page relative. I never ran Blogless in a subdir, so this never came up in my mind. :-)
