### ISSUE TITLE
Selection of theme not saved

### ISSUE THREAD

**Issue by Torsten-K** [datenbrei/blogless#4]
Hello,

I noticed that if I choose the theme Lessy, the choice is not saved, it always jumps back to the default theme. Tested with Vivaldi and Firefox under Linux.

**Comment by datenbrei** [comment]
Hi Torsten,


danke für den Hinweis, ich schaue es mir an. Bin allerdings erstmal im 
Urlaub. Ich melde mich dann bei Dir....


So long, Martin


Am 24.02.2017 um 14:50 schrieb Torsten Kelsch:

**Comment by Zegnat** [comment]
Fixed in #5.

@Torsten-K you can [copy the fix](https://github.com/datenbrei/blogless/pull/5/files#diff-aadcaadf90c12018b64f9ab1600284b6) easily enough, as only 3 lines have been changed.

**Comment by Torsten-K** [comment]
Danke/thanks, Martin/Zegnat!
